// @generated by OpenIM Contract Compiler; DO NOT EDIT.
package uts.sdk.modules.unixOpenimSdk

import org.json.JSONObject

/** Generated contract-ID adapter. Lifecycle state and callback arbitration stay in DriverRuntime. */
object OpenIMCoreAdapter {
  private const val LOCAL_ERROR_CODE = -1

  private fun localFailure(reject: OpenIMReject, error: Throwable) {
    reject(LOCAL_ERROR_CODE, error.message ?: "OpenIM platform driver failure")
  }

  fun callAsync(
    callableID: Number,
    operationID: String,
    requestJSON: String,
    resolve: OpenIMResolveString,
    reject: OpenIMReject
  ) {
    try {
      when (callableID.toInt()) {
        2051 -> resolve(NativeOpenIMSDK.initSDK(operationID, requestJSON))
        2052 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.login(operationID, request.getString("userID"), request.getString("token"), resolve, reject)
        }
        2053 -> NativeOpenIMSDK.logout(operationID, resolve, reject)
        2054 -> resolve(NativeOpenIMSDK.getLoginStatus(operationID))
        2055 -> resolve(NativeOpenIMSDK.getLoginUserID())
        2058 -> resolve(NativeOpenIMSDK.unInitSDK(operationID))
        2059 -> {
          NativeOpenIMSDK.getAllConversationList(operationID, resolve, reject)
        }
        2060 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getOneConversation(operationID, request.getDouble("sessionType"), request.getString("sourceID"), resolve, reject)
        }
        2061 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getAdvancedHistoryMessageList(operationID, request.getString("historyOptions"), resolve, reject)
        }
        2062 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getSpecifiedGroupsInfo(operationID, request.getString("groupIDList"), resolve, reject)
        }
        2063 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.deleteConversationAndDeleteAllMsg(operationID, request.getString("conversationID"), resolve, reject)
        }
        2064 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.markConversationMessageAsRead(operationID, request.getString("conversationID"), resolve, reject)
        }
        2065 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getGroupMemberList(operationID, request.getString("groupID"), request.getDouble("filter"), request.getDouble("offset"), request.getDouble("count"), resolve, reject)
        }
        2066 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setMessageLocalEx(operationID, request.getString("conversationID"), request.getString("clientMsgID"), request.getString("localEx"), resolve, reject)
        }
        2067 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.revokeMessage(operationID, request.getString("conversationID"), request.getString("clientMsgID"), resolve, reject)
        }
        2068 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setConversation(operationID, request.getString("conversationID"), request.getString("conversationInfo"), resolve, reject)
        }
        2069 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setAppBackgroundStatus(operationID, request.getBoolean("isBackground"), resolve, reject)
        }
        2070 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setAppBadge(operationID, request.getDouble("count"), resolve, reject)
        }
        2071 -> {
          NativeOpenIMSDK.networkStatusChanged(operationID, resolve, reject)
        }
        2072 -> {
          NativeOpenIMSDK.getSelfUserInfo(operationID, resolve, reject)
        }
        2073 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getUsersInfo(operationID, request.getString("userIDList"), resolve, reject)
        }
        2074 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setSelfInfo(operationID, request.getString("userInfo"), resolve, reject)
        }
        2075 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.deleteMessageFromLocalStorage(operationID, request.getString("conversationID"), request.getString("clientMsgID"), resolve, reject)
        }
        2076 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.deleteMessage(operationID, request.getString("conversationID"), request.getString("clientMsgID"), resolve, reject)
        }
        2077 -> {
          NativeOpenIMSDK.deleteAllMsgFromLocal(operationID, resolve, reject)
        }
        2078 -> {
          NativeOpenIMSDK.deleteAllMsgFromLocalAndSvr(operationID, resolve, reject)
        }
        2079 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.insertSingleMessageToLocalStorage(operationID, request.getString("message"), request.getString("recvID"), request.getString("sendID"), resolve, reject)
        }
        2080 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.insertGroupMessageToLocalStorage(operationID, request.getString("message"), request.getString("groupID"), request.getString("sendID"), resolve, reject)
        }
        2081 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.changeInputStates(operationID, request.getString("conversationID"), request.getBoolean("focus"), resolve, reject)
        }
        2082 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.clearConversationAndDeleteAllMsg(operationID, request.getString("conversationID"), resolve, reject)
        }
        2083 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.hideConversation(operationID, request.getString("conversationID"), resolve, reject)
        }
        2084 -> {
          NativeOpenIMSDK.hideAllConversations(operationID, resolve, reject)
        }
        2085 -> {
          NativeOpenIMSDK.markAllConversationMessageAsRead(operationID, resolve, reject)
        }
        2086 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.searchConversation(operationID, request.getString("searchParam"), resolve, reject)
        }
        2087 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getConversationListSplit(operationID, request.getDouble("offset"), request.getDouble("count"), resolve, reject)
        }
        2088 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.getConversationIDBySessionType(operationID, request.getString("sourceID"), request.getDouble("sessionType")))
        }
        2089 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getMultipleConversation(operationID, request.getString("conversationIDList"), resolve, reject)
        }
        2090 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.deleteConversationAndDeleteAllMsg(operationID, request.getString("conversationID"), resolve, reject)
        }
        2091 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.setConversationDraft(operationID, request.getString("conversationID"), request.getString("draftText"), resolve, reject)
        }
        2092 -> {
          NativeOpenIMSDK.getTotalUnreadMsgCount(operationID, resolve, reject)
        }
        2093 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.searchLocalMessages(operationID, request.getString("searchParams"), resolve, reject)
        }
        2094 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.addFriend(operationID, request.getString("friendRequest"), resolve, reject)
        }
        2095 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.searchFriends(operationID, request.getString("searchParams"), resolve, reject)
        }
        2096 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getSpecifiedFriendsInfo(operationID, request.getString("userIDList"), request.getBoolean("filterBlack"), resolve, reject)
        }
        2097 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getFriendApplicationListAsRecipient(operationID, request.getString("request"), resolve, reject)
        }
        2098 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getFriendApplicationListAsApplicant(operationID, request.getString("request"), resolve, reject)
        }
        2099 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getFriendApplicationUnhandledCount(operationID, request.getString("page"), resolve, reject)
        }
        2100 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getFriendList(operationID, request.getBoolean("filterBlack"), resolve, reject)
        }
        2101 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.getFriendListPage(operationID, request.getDouble("offset"), request.getDouble("count"), request.getBoolean("filterBlack"), resolve, reject)
        }
        2102 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.updateFriends(operationID, request.getString("friendInfo"), resolve, reject)
        }
        2103 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.checkFriend(operationID, request.getString("userIDList"), resolve, reject)
        }
        2104 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.acceptFriendApplication(operationID, request.getString("application"), resolve, reject)
        }
        2105 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.refuseFriendApplication(operationID, request.getString("application"), resolve, reject)
        }
        2106 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.deleteFriend(operationID, request.getString("userID"), resolve, reject)
        }
        2107 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.addBlack(operationID, request.getString("toUserID"), request.getString("ex"), resolve, reject)
        }
        2108 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.removeBlack(operationID, request.getString("userID"), resolve, reject)
        }
        2109 -> {
          NativeOpenIMSDK.getBlackList(operationID, resolve, reject)
        }
        2139 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createTextMessage(operationID, request.getString("text")))
        }
        2140 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createImageMessageFromFullPath(operationID, request.getString("imageFullPath")))
        }
        2141 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createImageMessageByURL(operationID, request.getString("sourcePath"), request.getString("sourcePicture"), request.getString("bigPicture"), request.getString("snapshotPicture")))
        }
        2142 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createCustomMessage(operationID, request.getString("data"), request.getString("extension"), request.getString("descriptionText")))
        }
        2143 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createQuoteMessage(operationID, request.getString("text"), request.getString("message")))
        }
        2144 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createAdvancedQuoteMessage(operationID, request.getString("text"), request.getString("message"), request.getString("messageEntityList")))
        }
        2145 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createAdvancedTextMessage(operationID, request.getString("text"), request.getString("messageEntityList")))
        }
        2146 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createTextAtMessage(operationID, request.getString("text"), request.getString("atUserIDList"), request.getString("atUsersInfo"), request.getString("quoteMessage")))
        }
        2147 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createSoundMessageFromFullPath(operationID, request.getString("soundPath"), request.getDouble("duration")))
        }
        2148 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createSoundMessageByURL(operationID, request.getString("soundInfo")))
        }
        2149 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createVideoMessageFromFullPath(operationID, request.getString("videoPath"), request.getString("videoType"), request.getDouble("duration"), request.getString("snapshotPath")))
        }
        2150 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createVideoMessageByURL(operationID, request.getString("videoInfo")))
        }
        2151 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createFileMessageFromFullPath(operationID, request.getString("filePath"), request.getString("fileName")))
        }
        2152 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createFileMessageByURL(operationID, request.getString("fileInfo")))
        }
        2153 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createMergerMessage(operationID, request.getString("messageList"), request.getString("title"), request.getString("abstractList")))
        }
        2154 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createForwardMessage(operationID, request.getString("message")))
        }
        2155 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createFaceMessage(operationID, request.getDouble("index"), request.getString("data")))
        }
        2156 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createLocationMessage(operationID, request.getString("descriptionText"), request.getDouble("longitude"), request.getDouble("latitude")))
        }
        2157 -> {
          val request = JSONObject(requestJSON)
          resolve(NativeOpenIMSDK.createCardMessage(operationID, request.getString("cardInfo")))
        }
        2158 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.sendMessage(operationID, request.getString("message"), request.getString("recvID"), request.getString("groupID"), request.getString("offlinePushInfo"), request.getBoolean("isOnlineOnly"), resolve, reject)
        }
        2159 -> {
          val request = JSONObject(requestJSON)
          NativeOpenIMSDK.sendMessageNotOss(operationID, request.getString("message"), request.getString("recvID"), request.getString("groupID"), request.getString("offlinePushInfo"), request.getBoolean("isOnlineOnly"), resolve, reject)
        }
        else -> reject(LOCAL_ERROR_CODE, "Unsupported OpenIM callable ID: " + callableID.toString())
      }
    } catch (error: Throwable) {
      localFailure(reject, error)
    }
  }

  fun callSync(callableID: Number, operationID: String, requestJSON: String): String {
    return when (callableID.toInt()) {
      2056 -> NativeOpenIMSDK.getSdkVersion()
      else -> throw IllegalArgumentException("Unsupported OpenIM callable ID: " + callableID.toString())
    }
  }

  fun bindEventSink(sink: OpenIMNativeEvent) {
    NativeOpenIMSDK.bindNativeEvents(sink)
  }
}
