import assert from 'node:assert/strict'
import test from 'node:test'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generatedDriverRuntime, verifyDriverInvariants } from '../src/verify-driver.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

test('native Drivers retain lifecycle and exactly-once seams', () => {
  verifyDriverInvariants(root)
})

test('Enterprise runtime comparison uses the generated source header', () => {
  const source = 'package example\n'
  const generated = '// @generated by OpenIM Contract Compiler; DO NOT EDIT.\npackage example\n'
  assert.equal(generatedDriverRuntime(source), generated)
  assert.equal(generatedDriverRuntime(generated), generated)
})
