import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generatedDriverRuntime, verifyDriverInvariants } from '../src/verify-driver.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

test('native Drivers retain lifecycle and exactly-once seams', () => {
  verifyDriverInvariants(root)
})

test('Enterprise runtime comparison uses the generated source header', () => {
  const source = 'package example\n'
  const generated = '// @generated by OpenIM Contract Compiler; DO NOT EDIT.\npackage example\n'
  assert.equal(generatedDriverRuntime(source), generated)
  assert.equal(generatedDriverRuntime(generated), generated)
})

test('Enterprise Harmony verification requires the ArkTS-safe typed native payload seam', () => {
  const verifier = readFileSync(resolve(root, 'tooling/src/verify-driver.ts'), 'utf8')
  assert.match(verifier, /private static parseNativePayload\(value: Object \| null\): OpenIMHarmonyNativePayload \| null/)
  assert.match(verifier, /const reasonObject: OpenIMHarmonyNativePayload \| null/)
  assert.match(verifier, /reasonObject\.errCode/)
  assert.match(verifier, /reasonObject\.errMsg/)
  assert.match(verifier, /\['parseJSONObject', 'readNativeValue\('\]/)
})
