import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generatedDriverRuntime, verifyDriverInvariants } from '../src/verify-driver.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

test('native Drivers retain lifecycle and exactly-once seams', () => {
  verifyDriverInvariants(root)
})

test('send-message progress is correlated by client message ID on both native bridges', () => {
  const contract = readFileSync(resolve(root, 'contracts/base/contract.json'), 'utf8')
  const android = readFileSync(resolve(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/NativeOpenIMSDK.kt'), 'utf8')
  const ios = readFileSync(resolve(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/NativeOpenIMSDK.swift'), 'utf8')

  assert.match(
    contract,
    /export type OpenIMSendMessageProgressEvent = \{\\n  clientMsgID : string\\n  progress : number\\n\}/,
  )
  assert.match(android, /private val clientMsgID: String/)
  assert.match(android, /\.put\("clientMsgID", clientMsgID\)/)
  assert.doesNotMatch(android, /\.put\("operationID", operationID\)/)
  assert.match(ios, /private let clientMsgID: String/)
  assert.match(ios, /"clientMsgID": clientMsgID/)
  assert.doesNotMatch(ios, /"operationID": operationID/)
})

test('Enterprise runtime comparison uses the generated source header', () => {
  const source = 'package example\n'
  const generated = '// @generated by OpenIM Contract Compiler; DO NOT EDIT.\npackage example\n'
  assert.equal(generatedDriverRuntime(source), generated)
  assert.equal(generatedDriverRuntime(generated), generated)
})

test('Enterprise Harmony verification requires the ArkTS-safe typed native payload seam', () => {
  const verifier = readFileSync(resolve(root, 'tooling/src/verify-driver.ts'), 'utf8')
  assert.match(verifier, /private static parseNativePayload\(value: Object \| null\): OpenIMHarmonyNativePayload \| null/)
  assert.match(verifier, /const reasonObject: OpenIMHarmonyNativePayload \| null/)
  assert.match(verifier, /reasonObject\.errCode/)
  assert.match(verifier, /reasonObject\.errMsg/)
  assert.match(verifier, /\['parseJSONObject', 'readNativeValue\('\]/)
})
