// @generated by OpenIM Contract Compiler; DO NOT EDIT.
import Foundation
import CoreFoundation

/// Generated contract-ID adapter. Lifecycle state and callback arbitration stay in DriverRuntime.
class OpenIMCoreAdapter {
    private static let localErrorCode = NSNumber(value: -1)

    private static func localFailure(_ reject: @escaping OpenIMReject, _ error: Error) {
        reject(localErrorCode, error.localizedDescription)
    }

    private static func requestObject(_ requestJSON: String) throws -> [String: Any] {
        let data = Data(requestJSON.utf8)
        guard let request = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Invalid request JSON object"])
        }
        return request
    }

    private static func requiredString(_ request: [String: Any], _ name: String) throws -> String {
        guard let value = request[name] as? String else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Missing request string: \(name)"])
        }
        return value
    }

    private static func requiredBool(_ request: [String: Any], _ name: String) throws -> Bool {
        guard let value = request[name] as? Bool else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Missing request boolean: \(name)"])
        }
        return value
    }

    private static func requiredNumber(_ request: [String: Any], _ name: String) throws -> NSNumber {
        guard let value = request[name] as? NSNumber, CFGetTypeID(value) != CFBooleanGetTypeID() else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Missing request number: \(name)"])
        }
        return value
    }

    private static func loginRequest(_ requestJSON: String) throws -> (String, String) {
        let request = try requestObject(requestJSON)
        return (try requiredString(request, "userID"), try requiredString(request, "token"))
    }

    static func callAsync(
        _ callableID: NSNumber,
        _ operationID: String,
        _ requestJSON: String,
        _ resolve: @escaping OpenIMResolveString,
        _ reject: @escaping OpenIMReject
    ) {
        do {
            switch callableID.intValue {
            case 2051:
                resolve(NativeOpenIMSDK.initSDK(operationID, requestJSON))
            case 2052:
                let request = try loginRequest(requestJSON)
                NativeOpenIMSDK.login(operationID, request.0, request.1, resolve, reject)
            case 2053:
                NativeOpenIMSDK.logout(operationID, resolve, reject)
            case 2054:
                resolve(NativeOpenIMSDK.getLoginStatus(operationID))
            case 2055:
                resolve(NativeOpenIMSDK.getLoginUserID())
            case 2058:
                resolve(NativeOpenIMSDK.unInitSDK(operationID))
            case 2059:
                NativeOpenIMSDK.getAllConversationList(operationID, resolve, reject)
            case 2060:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getOneConversation(operationID, try requiredNumber(request, "sessionType"), try requiredString(request, "sourceID"), resolve, reject)
            case 2061:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getAdvancedHistoryMessageList(operationID, try requiredString(request, "historyOptions"), resolve, reject)
            case 2062:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getSpecifiedGroupsInfo(operationID, try requiredString(request, "groupIDList"), resolve, reject)
            case 2063:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.deleteConversationAndDeleteAllMsg(operationID, try requiredString(request, "conversationID"), resolve, reject)
            case 2064:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.markConversationMessageAsRead(operationID, try requiredString(request, "conversationID"), resolve, reject)
            case 2065:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getGroupMemberList(operationID, try requiredString(request, "groupID"), try requiredNumber(request, "filter"), try requiredNumber(request, "offset"), try requiredNumber(request, "count"), resolve, reject)
            case 2066:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setMessageLocalEx(operationID, try requiredString(request, "conversationID"), try requiredString(request, "clientMsgID"), try requiredString(request, "localEx"), resolve, reject)
            case 2067:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.revokeMessage(operationID, try requiredString(request, "conversationID"), try requiredString(request, "clientMsgID"), resolve, reject)
            case 2068:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setConversation(operationID, try requiredString(request, "conversationID"), try requiredString(request, "conversationInfo"), resolve, reject)
            case 2069:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setAppBackgroundStatus(operationID, try requiredBool(request, "isBackground"), resolve, reject)
            case 2070:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setAppBadge(operationID, try requiredNumber(request, "count"), resolve, reject)
            case 2071:
                NativeOpenIMSDK.networkStatusChanged(operationID, resolve, reject)
            case 2072:
                NativeOpenIMSDK.getSelfUserInfo(operationID, resolve, reject)
            case 2073:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getUsersInfo(operationID, try requiredString(request, "userIDList"), resolve, reject)
            case 2074:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setSelfInfo(operationID, try requiredString(request, "userInfo"), resolve, reject)
            case 2075:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.deleteMessageFromLocalStorage(operationID, try requiredString(request, "conversationID"), try requiredString(request, "clientMsgID"), resolve, reject)
            case 2076:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.deleteMessage(operationID, try requiredString(request, "conversationID"), try requiredString(request, "clientMsgID"), resolve, reject)
            case 2077:
                NativeOpenIMSDK.deleteAllMsgFromLocal(operationID, resolve, reject)
            case 2078:
                NativeOpenIMSDK.deleteAllMsgFromLocalAndSvr(operationID, resolve, reject)
            case 2079:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.insertSingleMessageToLocalStorage(operationID, try requiredString(request, "message"), try requiredString(request, "recvID"), try requiredString(request, "sendID"), resolve, reject)
            case 2080:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.insertGroupMessageToLocalStorage(operationID, try requiredString(request, "message"), try requiredString(request, "groupID"), try requiredString(request, "sendID"), resolve, reject)
            case 2081:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.changeInputStates(operationID, try requiredString(request, "conversationID"), try requiredBool(request, "focus"), resolve, reject)
            case 2082:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.clearConversationAndDeleteAllMsg(operationID, try requiredString(request, "conversationID"), resolve, reject)
            case 2083:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.hideConversation(operationID, try requiredString(request, "conversationID"), resolve, reject)
            case 2084:
                NativeOpenIMSDK.hideAllConversations(operationID, resolve, reject)
            case 2085:
                NativeOpenIMSDK.markAllConversationMessageAsRead(operationID, resolve, reject)
            case 2086:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.searchConversation(operationID, try requiredString(request, "searchParam"), resolve, reject)
            case 2087:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getConversationListSplit(operationID, try requiredNumber(request, "offset"), try requiredNumber(request, "count"), resolve, reject)
            case 2088:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.getConversationIDBySessionType(operationID, try requiredString(request, "sourceID"), try requiredNumber(request, "sessionType")))
            case 2089:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getMultipleConversation(operationID, try requiredString(request, "conversationIDList"), resolve, reject)
            case 2090:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.deleteConversationAndDeleteAllMsg(operationID, try requiredString(request, "conversationID"), resolve, reject)
            case 2091:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setConversationDraft(operationID, try requiredString(request, "conversationID"), try requiredString(request, "draftText"), resolve, reject)
            case 2092:
                NativeOpenIMSDK.getTotalUnreadMsgCount(operationID, resolve, reject)
            case 2093:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.searchLocalMessages(operationID, try requiredString(request, "searchParams"), resolve, reject)
            case 2094:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.addFriend(operationID, try requiredString(request, "friendRequest"), resolve, reject)
            case 2095:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.searchFriends(operationID, try requiredString(request, "searchParams"), resolve, reject)
            case 2096:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getSpecifiedFriendsInfo(operationID, try requiredString(request, "userIDList"), try requiredBool(request, "filterBlack"), resolve, reject)
            case 2097:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getFriendApplicationListAsRecipient(operationID, try requiredString(request, "request"), resolve, reject)
            case 2098:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getFriendApplicationListAsApplicant(operationID, try requiredString(request, "request"), resolve, reject)
            case 2099:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getFriendApplicationUnhandledCount(operationID, try requiredString(request, "page"), resolve, reject)
            case 2100:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getFriendList(operationID, try requiredBool(request, "filterBlack"), resolve, reject)
            case 2101:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getFriendListPage(operationID, try requiredNumber(request, "offset"), try requiredNumber(request, "count"), try requiredBool(request, "filterBlack"), resolve, reject)
            case 2102:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.updateFriends(operationID, try requiredString(request, "friendInfo"), resolve, reject)
            case 2103:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.checkFriend(operationID, try requiredString(request, "userIDList"), resolve, reject)
            case 2104:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.acceptFriendApplication(operationID, try requiredString(request, "application"), resolve, reject)
            case 2105:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.refuseFriendApplication(operationID, try requiredString(request, "application"), resolve, reject)
            case 2106:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.deleteFriend(operationID, try requiredString(request, "userID"), resolve, reject)
            case 2107:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.addBlack(operationID, try requiredString(request, "toUserID"), try requiredString(request, "ex"), resolve, reject)
            case 2108:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.removeBlack(operationID, try requiredString(request, "userID"), resolve, reject)
            case 2109:
                NativeOpenIMSDK.getBlackList(operationID, resolve, reject)
            case 2110:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.inviteUserToGroup(operationID, try requiredString(request, "groupID"), try requiredString(request, "reason"), try requiredString(request, "userIDList"), resolve, reject)
            case 2111:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.kickGroupMember(operationID, try requiredString(request, "groupID"), try requiredString(request, "reason"), try requiredString(request, "userIDList"), resolve, reject)
            case 2112:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.isJoinGroup(operationID, try requiredString(request, "groupID"), resolve, reject)
            case 2113:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getSpecifiedGroupMembersInfo(operationID, try requiredString(request, "groupID"), try requiredString(request, "userIDList"), resolve, reject)
            case 2114:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getUsersInGroup(operationID, try requiredString(request, "groupID"), try requiredString(request, "userIDList"), resolve, reject)
            case 2115:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.searchGroupMembers(operationID, try requiredString(request, "searchParams"), resolve, reject)
            case 2116:
                NativeOpenIMSDK.getJoinedGroupList(operationID, resolve, reject)
            case 2117:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getJoinedGroupListPage(operationID, try requiredNumber(request, "offset"), try requiredNumber(request, "count"), resolve, reject)
            case 2118:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.createGroup(operationID, try requiredString(request, "groupInfo"), resolve, reject)
            case 2119:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setGroupInfo(operationID, try requiredString(request, "groupInfo"), resolve, reject)
            case 2120:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.setGroupMemberInfo(operationID, try requiredString(request, "memberInfo"), resolve, reject)
            case 2121:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.joinGroup(operationID, try requiredString(request, "groupID"), try requiredString(request, "reqMsg"), try requiredNumber(request, "joinSource"), try requiredString(request, "ex"), resolve, reject)
            case 2122:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.searchGroups(operationID, try requiredString(request, "searchParams"), resolve, reject)
            case 2123:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.quitGroup(operationID, try requiredString(request, "groupID"), resolve, reject)
            case 2124:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.dismissGroup(operationID, try requiredString(request, "groupID"), resolve, reject)
            case 2125:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.changeGroupMute(operationID, try requiredString(request, "groupID"), try requiredBool(request, "isMute"), resolve, reject)
            case 2126:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.changeGroupMemberMute(operationID, try requiredString(request, "groupID"), try requiredString(request, "userID"), try requiredNumber(request, "mutedSeconds"), resolve, reject)
            case 2127:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.transferGroupOwner(operationID, try requiredString(request, "groupID"), try requiredString(request, "newOwnerUserID"), resolve, reject)
            case 2128:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getGroupApplicationListAsApplicant(operationID, try requiredString(request, "request"), resolve, reject)
            case 2129:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getGroupApplicationListAsRecipient(operationID, try requiredString(request, "request"), resolve, reject)
            case 2130:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getGroupApplicationUnhandledCount(operationID, try requiredString(request, "page"), resolve, reject)
            case 2131:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.acceptGroupApplication(operationID, try requiredString(request, "groupID"), try requiredString(request, "fromUserID"), try requiredString(request, "handleMsg"), resolve, reject)
            case 2132:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.refuseGroupApplication(operationID, try requiredString(request, "groupID"), try requiredString(request, "fromUserID"), try requiredString(request, "handleMsg"), resolve, reject)
            case 2133:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.findMessageList(operationID, try requiredString(request, "findParams"), resolve, reject)
            case 2134:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.updateFcmToken(operationID, try requiredString(request, "fcmToken"), try requiredNumber(request, "expireTime"), resolve, reject)
            case 2135:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.subscribeUsersStatus(operationID, try requiredString(request, "userIDList"), resolve, reject)
            case 2136:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.unsubscribeUsersStatus(operationID, try requiredString(request, "userIDList"), resolve, reject)
            case 2137:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.getUserStatus(operationID, try requiredString(request, "userIDList"), resolve, reject)
            case 2138:
                NativeOpenIMSDK.getSubscribeUsersStatus(operationID, resolve, reject)
            case 2139:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createTextMessage(operationID, try requiredString(request, "text")))
            case 2140:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createImageMessageFromFullPath(operationID, try requiredString(request, "imageFullPath")))
            case 2141:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createImageMessageByURL(operationID, try requiredString(request, "sourcePath"), try requiredString(request, "sourcePicture"), try requiredString(request, "bigPicture"), try requiredString(request, "snapshotPicture")))
            case 2142:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createCustomMessage(operationID, try requiredString(request, "data"), try requiredString(request, "extension"), try requiredString(request, "descriptionText")))
            case 2143:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createQuoteMessage(operationID, try requiredString(request, "text"), try requiredString(request, "message")))
            case 2144:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createAdvancedQuoteMessage(operationID, try requiredString(request, "text"), try requiredString(request, "message"), try requiredString(request, "messageEntityList")))
            case 2145:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createAdvancedTextMessage(operationID, try requiredString(request, "text"), try requiredString(request, "messageEntityList")))
            case 2146:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createTextAtMessage(operationID, try requiredString(request, "text"), try requiredString(request, "atUserIDList"), try requiredString(request, "atUsersInfo"), try requiredString(request, "quoteMessage")))
            case 2147:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createSoundMessageFromFullPath(operationID, try requiredString(request, "soundPath"), try requiredNumber(request, "duration")))
            case 2148:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createSoundMessageByURL(operationID, try requiredString(request, "soundInfo")))
            case 2149:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createVideoMessageFromFullPath(operationID, try requiredString(request, "videoPath"), try requiredString(request, "videoType"), try requiredNumber(request, "duration"), try requiredString(request, "snapshotPath")))
            case 2150:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createVideoMessageByURL(operationID, try requiredString(request, "videoInfo")))
            case 2151:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createFileMessageFromFullPath(operationID, try requiredString(request, "filePath"), try requiredString(request, "fileName")))
            case 2152:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createFileMessageByURL(operationID, try requiredString(request, "fileInfo")))
            case 2153:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createMergerMessage(operationID, try requiredString(request, "messageList"), try requiredString(request, "title"), try requiredString(request, "abstractList")))
            case 2154:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createForwardMessage(operationID, try requiredString(request, "message")))
            case 2155:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createFaceMessage(operationID, try requiredNumber(request, "index"), try requiredString(request, "data")))
            case 2156:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createLocationMessage(operationID, try requiredString(request, "descriptionText"), try requiredNumber(request, "longitude"), try requiredNumber(request, "latitude")))
            case 2157:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createCardMessage(operationID, try requiredString(request, "cardInfo")))
            case 2158:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.sendMessage(operationID, try requiredString(request, "message"), try requiredString(request, "recvID"), try requiredString(request, "groupID"), try requiredString(request, "offlinePushInfo"), try requiredBool(request, "isOnlineOnly"), resolve, reject)
            case 2159:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.sendMessageNotOss(operationID, try requiredString(request, "message"), try requiredString(request, "recvID"), try requiredString(request, "groupID"), try requiredString(request, "offlinePushInfo"), try requiredBool(request, "isOnlineOnly"), resolve, reject)
            case 2160:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.uploadFile(operationID, try requiredString(request, "uploadParams"), resolve, reject)
            case 2161:
                let request = try requestObject(requestJSON)
                NativeOpenIMSDK.uploadLogs(operationID, try requiredNumber(request, "line"), try requiredString(request, "ex"), resolve, reject)
            default:
                reject(localErrorCode, "Unsupported OpenIM callable ID: \(callableID)")
            }
        } catch {
            localFailure(reject, error)
        }
    }

    static func callSync(_ callableID: NSNumber, _ operationID: String, _ requestJSON: String) -> String {
        switch callableID.intValue {
        case 2056:
            return NativeOpenIMSDK.getSdkVersion()
        default:
            preconditionFailure("Unsupported OpenIM callable ID: \(callableID)")
        }
    }

    static func bindEventSink(_ sink: @escaping OpenIMNativeEvent) {
        NativeOpenIMSDK.bindNativeEvents(sink)
    }
}
