// @generated by OpenIM Contract Compiler; DO NOT EDIT.
import Foundation

/// Generated contract-ID adapter. Lifecycle state and callback arbitration stay in DriverRuntime.
class OpenIMCoreAdapter {
    private static let localErrorCode = NSNumber(value: -1)

    private static func localFailure(_ reject: @escaping OpenIMReject, _ error: Error) {
        reject(localErrorCode, error.localizedDescription)
    }

    private static func loginRequest(_ requestJSON: String) throws -> (String, String) {
        let data = Data(requestJSON.utf8)
        guard let request = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let userID = request["userID"] as? String,
              let token = request["token"] as? String else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Invalid login request JSON"])
        }
        return (userID, token)
    }

    static func callAsync(
        _ callableID: NSNumber,
        _ operationID: String,
        _ requestJSON: String,
        _ resolve: @escaping OpenIMResolveString,
        _ reject: @escaping OpenIMReject
    ) {
        do {
            switch callableID.intValue {
            case 2051:
                resolve(NativeOpenIMSDK.initSDK(operationID, requestJSON))
            case 2052:
                let request = try loginRequest(requestJSON)
                NativeOpenIMSDK.login(operationID, request.0, request.1, resolve, reject)
            case 2053:
                NativeOpenIMSDK.logout(operationID, resolve, reject)
            case 2054:
                resolve(NativeOpenIMSDK.getLoginStatus(operationID))
            case 2055:
                resolve(NativeOpenIMSDK.getLoginUserID())
            case 2058:
                resolve(NativeOpenIMSDK.unInitSDK(operationID))
            default:
                reject(localErrorCode, "Unsupported OpenIM callable ID: \(callableID)")
            }
        } catch {
            localFailure(reject, error)
        }
    }

    static func callSync(_ callableID: NSNumber, _ operationID: String, _ requestJSON: String) -> String {
        switch callableID.intValue {
        case 2056:
            return NativeOpenIMSDK.getSdkVersion()
        default:
            preconditionFailure("Unsupported OpenIM callable ID: \(callableID)")
        }
    }

    static func bindEventSink(_ sink: @escaping OpenIMNativeEvent) {
        NativeOpenIMSDK.bindNativeEvents(sink)
    }
}
