// @generated by OpenIM Contract Compiler; DO NOT EDIT.
import Foundation

/// Generated contract-ID adapter. Lifecycle state and callback arbitration stay in DriverRuntime.
class OpenIMCoreAdapter {
    private static let localErrorCode = NSNumber(value: -1)

    private static func localFailure(_ reject: @escaping OpenIMReject, _ error: Error) {
        reject(localErrorCode, error.localizedDescription)
    }

    private static func requestObject(_ requestJSON: String) throws -> [String: Any] {
        let data = Data(requestJSON.utf8)
        guard let request = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Invalid request JSON object"])
        }
        return request
    }

    private static func requiredString(_ request: [String: Any], _ name: String) throws -> String {
        guard let value = request[name] as? String else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Missing request string: \(name)"])
        }
        return value
    }

    private static func loginRequest(_ requestJSON: String) throws -> (String, String) {
        let request = try requestObject(requestJSON)
        return (try requiredString(request, "userID"), try requiredString(request, "token"))
    }

    private static func sendMessage(
        _ requestJSON: String,
        _ operationID: String,
        _ withoutOss: Bool,
        _ resolve: @escaping OpenIMResolveString,
        _ reject: @escaping OpenIMReject
    ) throws {
        let request = try requestObject(requestJSON)
        let message = try requiredString(request, "message")
        let recvID = try requiredString(request, "recvID")
        let groupID = try requiredString(request, "groupID")
        let offlinePushInfo = try requiredString(request, "offlinePushInfo")
        guard let isOnlineOnly = request["isOnlineOnly"] as? Bool else {
            throw NSError(domain: "OpenIMPlatformDriver", code: -1, userInfo: [NSLocalizedDescriptionKey: "Missing request boolean: isOnlineOnly"])
        }
        if withoutOss {
            NativeOpenIMSDK.sendMessageNotOss(operationID, message, recvID, groupID, offlinePushInfo, isOnlineOnly, resolve, reject)
        } else {
            NativeOpenIMSDK.sendMessage(operationID, message, recvID, groupID, offlinePushInfo, isOnlineOnly, resolve, reject)
        }
    }

    static func callAsync(
        _ callableID: NSNumber,
        _ operationID: String,
        _ requestJSON: String,
        _ resolve: @escaping OpenIMResolveString,
        _ reject: @escaping OpenIMReject
    ) {
        do {
            switch callableID.intValue {
            case 2051:
                resolve(NativeOpenIMSDK.initSDK(operationID, requestJSON))
            case 2052:
                let request = try loginRequest(requestJSON)
                NativeOpenIMSDK.login(operationID, request.0, request.1, resolve, reject)
            case 2053:
                NativeOpenIMSDK.logout(operationID, resolve, reject)
            case 2054:
                resolve(NativeOpenIMSDK.getLoginStatus(operationID))
            case 2055:
                resolve(NativeOpenIMSDK.getLoginUserID())
            case 2058:
                resolve(NativeOpenIMSDK.unInitSDK(operationID))
            case 2139:
                let request = try requestObject(requestJSON)
                resolve(NativeOpenIMSDK.createTextMessage(operationID, try requiredString(request, "text")))
            case 2158:
                try sendMessage(requestJSON, operationID, false, resolve, reject)
            case 2159:
                try sendMessage(requestJSON, operationID, true, resolve, reject)
            default:
                reject(localErrorCode, "Unsupported OpenIM callable ID: \(callableID)")
            }
        } catch {
            localFailure(reject, error)
        }
    }

    static func callSync(_ callableID: NSNumber, _ operationID: String, _ requestJSON: String) -> String {
        switch callableID.intValue {
        case 2056:
            return NativeOpenIMSDK.getSdkVersion()
        default:
            preconditionFailure("Unsupported OpenIM callable ID: \(callableID)")
        }
    }

    static func bindEventSink(_ sink: @escaping OpenIMNativeEvent) {
        NativeOpenIMSDK.bindNativeEvents(sink)
    }
}
