import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { ContractCallable, ContractDocument, ContractEvent, DriverRequestField, Platform, SurfaceSnapshot } from './model.js'
import { INDEX_MARKERS } from './template-authority.js'
import { withComputedSemanticHashes } from './contract-integrity.js'
import { sha256 } from './source.js'
import { buildPublicResponseSchemas, buildPublicTestDisposition } from './test-contract.js'
import { renderNativeCoreAdapter, renderPlatformDriverUTS } from './platform-driver.js'

export interface GeneratedOutput {
  path: string
  content: string
}

export const GENERATED_SOURCE_HEADER = '// @generated by OpenIM Contract Compiler; DO NOT EDIT.'

export function generatedSource(content: string): string {
  const normalized = content.trimEnd()
  return `${normalized.startsWith(GENERATED_SOURCE_HEADER) ? normalized : `${GENERATED_SOURCE_HEADER}\n${normalized}`}\n`
}

function readContract(root: string): ContractDocument {
  return JSON.parse(readFileSync(join(root, 'contracts/base/contract.json'), 'utf8')) as ContractDocument
}

function splitSignatureParameters(value: string): string[] {
  const result: string[] = []
  let start = 0
  let depth = 0
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index]
    if (character === '<' || character === '(' || character === '[' || character === '{') depth += 1
    else if (character === '>' || character === ')' || character === ']' || character === '}') depth -= 1
    else if (character === ',' && depth === 0) {
      result.push(value.slice(start, index))
      start = index + 1
    }
  }
  if (value.slice(start).trim() !== '') result.push(value.slice(start))
  return result
}

function formatType(value: string): string {
  return value.trim().replace(/\s*\|\s*/g, ' | ')
}

function callableSignatureParts(callable: ContractCallable): { parameters: string; returnType: string } {
  const prefix = `${callable.name}(`
  const separator = callable.signature.lastIndexOf('):')
  if (!callable.signature.startsWith(prefix) || separator < prefix.length) {
    throw new Error(`Invalid callable signature: ${callable.signature}`)
  }
  const parameters = splitSignatureParameters(callable.signature.slice(prefix.length, separator)).map((parameter) => {
    const match = /^([A-Za-z_$][\w$]*)(\?)?:(.+)$/.exec(parameter.trim())
    if (match == null) throw new Error(`Invalid callable parameter in ${callable.signature}: ${parameter}`)
    return `${match[1]}${match[2] == null ? ' :' : ' ?:'} ${formatType(match[3] ?? '')}`
  }).join(', ')
  return { parameters, returnType: formatType(callable.signature.slice(separator + 2)) }
}

function promiseValueType(returnType: string): string {
  const match = /^Promise<(.+)>$/.exec(returnType)
  if (match == null) throw new Error(`PlatformDriver async lowering requires Promise return type: ${returnType}`)
  return match[1] ?? ''
}

function driverRequestFieldSource(field: DriverRequestField): string {
  if (field.parameter == null) throw new Error(`Driver request field ${field.name} requires a parameter`)
  return field.member == null ? field.parameter : `${field.parameter}.${field.member}`
}

function driverRequestFieldExpression(field: DriverRequestField, platform: 'android' | 'ios'): string {
  if (field.codec === 'literal') {
    if (field.value == null) throw new Error(`Literal Driver request field ${field.name} requires a value`)
    return JSON.stringify(field.value)
  }
  const source = driverRequestFieldSource(field)
  if (field.codec === 'identity') return source
  if (field.codec === 'json') return `stringifyJSON(${source})`
  if (field.codec === 'file-json') return platform === 'ios' ? `stringifyOpenIMFileElem(${source})` : `stringifyJSON(${source})`
  if (field.codec === 'local-media-path') return platform === 'ios' ? `normalizeIOSLocalMediaPath(${source})` : source
  if (field.codec === 'message-entity-list-json') return platform === 'ios' ? `stringifyOpenIMMessageEntityList(${source})` : `stringifyJSON(${source})`
  if (field.codec === 'message-json') return `stringifyOpenIMMessage(${source})`
  if (field.codec === 'message-list-json') return platform === 'ios' ? `stringifyOpenIMMessageList(${source})` : `stringifyOpenIMMessagePayload(${source})`
  if (field.codec === 'optional-message-json') return `${source} != null ? stringifyOpenIMMessage(${source}) : ''`
  if (field.codec === 'optional-boolean') return `optionalBoolean(${source})`
  if (field.codec === 'optional-string') return `optionalString(${source})`
  if (field.codec === 'picture-json') return platform === 'ios' ? `stringifyOpenIMPicture(${source})` : `stringifyJSON(${source})`
  if (field.codec === 'set-group-info-json') return `stringifySetGroupInfoPayload(${source})`
  if (field.codec === 'set-group-member-info-json') return `stringifySetGroupMemberInfoPayload(${source})`
  if (field.codec === 'sound-json') return platform === 'ios' ? `stringifyOpenIMSoundElem(${source})` : `stringifyJSON(${source})`
  if (field.codec === 'stored-message-json') return platform === 'ios' ? `stringifyOpenIMMessage(${source})` : `stringifyOpenIMMessagePayload(${source})`
  if (field.codec === 'update-friends-json') return `stringifyUpdateFriendsPayload(${source})`
  if (field.codec === 'video-json') return platform === 'ios' ? `stringifyOpenIMVideoElem(${source})` : `stringifyJSON(${source})`
  if (field.codec === 'offline-push-json') return `readOfflinePushInfo(${field.parameter})`
  if (field.codec === 'online-only') return `readIsOnlineOnly(${field.parameter})`
  throw new Error(`Unsupported Driver request field codec: ${field.codec}`)
}

function driverRequestFieldPreconditions(callable: ContractCallable, field: DriverRequestField, platform: 'android' | 'ios'): string[] {
  if (platform !== 'ios' || field.codec !== 'local-media-path') return []
  const source = driverRequestFieldSource(field)
  return [`if (rejectUnsupportedIOSLocalMediaPath('${callable.name}', ${source}, reject)) { return };`]
}

function driverFieldsRequestPrelude(fields: DriverRequestField[], platform: 'android' | 'ios'): string {
  if (fields.length === 0) throw new Error('Driver fields request must contain at least one field')
  const fragments = fields.map((field, index) => {
    const prefix = index === 0 ? `'{"${field.name}":'` : `',"${field.name}":'`
    return `${prefix} + stringifyJSON(${driverRequestFieldExpression(field, platform)})`
  })
  return `const requestJSON = ${fragments.join(' + ')} + '}';`
}

const DRIVER_TYPED_RESPONSE_PARSERS: Readonly<Record<string, string>> = {
  'typed:OpenIMLoginStatus': 'parseNativeLoginStatus',
  'typed:OpenIMMessageItem|null': 'parseNativeMessage',
  'typed:OpenIMSearchMessageResult|null': 'parseNativeSearchMessageResult',
  'typed:OpenIMUploadFileResult|null': 'parseNativeUploadFileResult',
}

const DRIVER_PROMISE_RESPONSE_RESOLVERS: Readonly<Record<string, string>> = {
  'raw-string': 'resolveStringNative',
  'number': 'resolveNumberNative',
  'boolean': 'resolveBooleanNative',
  'typed:Array<string>|null': 'resolveStringListNative',
  'typed:OpenIMAdvancedHistoryMessageListResult|null': 'resolveAdvancedHistoryNative',
  'typed:OpenIMBlackListResult|null': 'resolveBlackListNative',
  'typed:OpenIMCheckFriendResult|null': 'resolveCheckFriendNative',
  'typed:OpenIMConversationItem|null': 'resolveConversationObjectNative',
  'typed:OpenIMConversationListResult|null': 'resolveConversationListNative',
  'typed:OpenIMFindMessageResult|null': 'resolveMessageListNative',
  'typed:OpenIMFriendApplicationListResult|null': 'resolveFriendApplicationListNative',
  'typed:OpenIMFriendListResult|null': 'resolveFriendListNative',
  'typed:OpenIMGroupApplicationListResult|null': 'resolveGroupApplicationListNative',
  'typed:OpenIMGroupItem|null': 'resolveGroupObjectNative',
  'typed:OpenIMGroupListResult|null': 'resolveGroupListNative',
  'typed:OpenIMGroupMemberListResult|null': 'resolveGroupMemberListNative',
  'typed:OpenIMUserInfo|null': 'resolveUserObjectNative',
  'typed:OpenIMUserListResult|null': 'resolveUserListNative',
  'typed:OpenIMUserStatusListResult|null': 'resolveUserStatusListNative',
}

function driverResolveExpression(callable: ContractCallable): string {
  if (callable.responseCodec === 'typed:OpenIMMessageItem') {
    return `(data : string) => { resolveSendMessageData(data, '${callable.name}', resolve, reject) }`
  }
  const parser = DRIVER_TYPED_RESPONSE_PARSERS[callable.responseCodec]
  if (parser != null) return `(data : string) => { resolve(${parser}(data)) }`
  throw new Error(`Unsupported PlatformDriver response codec for ${callable.name}: ${callable.responseCodec}`)
}

function renderLoweredCallable(callable: ContractCallable, platform: 'android' | 'ios'): string {
  const lowering = callable.lowering
  if (lowering == null) throw new Error(`Missing callable lowering: ${callable.name}`)
  const { parameters, returnType } = callableSignatureParts(callable)
  if (lowering.kind === 'event-control') {
    const expectedName = lowering.action === 'remove-subscription' ? 'off' : 'offAll'
    if (callable.name !== expectedName) throw new Error(`Invalid event-control lowering for ${callable.name}`)
    const call = lowering.action === 'remove-subscription'
      ? 'offSDKEvent(subscription)'
      : 'offAllSDKEvents(eventName)'
    return `export function ${callable.name}(${parameters}) { ${call} }`
  }
  if (lowering.kind === 'local-helper') {
    if (callable.completion !== 'sync') throw new Error(`Local helper lowering must be synchronous: ${callable.name}`)
    if (parameters.trim() !== '') throw new Error(`Local helper lowering does not support parameters: ${callable.name}`)
    const binding = callable.binding[platform]
    if (binding?.kind !== 'facade-alias' || binding.symbol !== lowering.symbol) {
      throw new Error(`Local helper binding mismatch for ${callable.name} on ${platform}`)
    }
    return `export const ${callable.name} = function () : ${returnType} { return ${lowering.symbol}() }`
  }
  if (lowering.kind === 'event-subscription') {
    if (callable.role !== 'event-subscription' || callable.completion !== 'sync') {
      throw new Error(`Invalid event subscription lowering for ${callable.name}`)
    }
    if (lowering.eventName !== callable.name || parameters.startsWith('handler : ') === false) {
      throw new Error(`Event subscription identity mismatch for ${callable.name}`)
    }
    const binding = callable.binding[platform]
    if (binding?.kind !== 'event' || binding.symbol !== lowering.eventName) {
      throw new Error(`Event subscription binding mismatch for ${callable.name} on ${platform}`)
    }
    return `@UTSJS.keepAlive\nexport function ${callable.name}(${parameters}) : ${returnType} { return ${lowering.eventName}Event(handler) }`
  }

  const prelude: string[] = []
  let operationID: string
  if (lowering.operationID === 'send-options') operationID = 'readOperationID(options)'
  else if (lowering.operationID === 'parameter' && lowering.precondition === 'logged-in-create') {
    operationID = 'op'
    prelude.push(`const op = normalizeOperationID(operationID); if (requireLoggedInForCreate('${callable.name}', op, reject) == false) { return };`)
  } else if (lowering.operationID === 'parameter') operationID = 'normalizeOperationID(operationID)'
  else operationID = "''"
  let requestExpression: string
  if (lowering.request === 'init-config') requestExpression = 'normalizeInitConfig(config)'
  else if (lowering.request === 'login-credentials') {
    requestExpression = 'requestJSON'
    prelude.push(`const requestJSON = '{"userID":' + stringifyJSON(userID) + ',"token":' + stringifyJSON(token) + '}';`)
  } else if (typeof lowering.request === 'object' && lowering.request.kind === 'fields') {
    requestExpression = 'requestJSON'
    for (const field of lowering.request.fields) prelude.push(...driverRequestFieldPreconditions(callable, field, platform))
    prelude.push(driverFieldsRequestPrelude(lowering.request.fields, platform))
  } else requestExpression = "'{}'"
  const requestPrelude = prelude.length === 0 ? '' : `${prelude.join(' ')} `

  if (lowering.transport === 'sync') {
    if (callable.completion !== 'sync') throw new Error(`Sync lowering has non-sync completion: ${callable.name}`)
    return `export const ${callable.name} = function (${parameters}) : ${returnType} { return driverCallSync(${callable.id}, ${operationID}, ${requestExpression}) }`
  }
  if (callable.completion === 'sync') throw new Error(`Async lowering has sync completion: ${callable.name}`)
  const bindEvents = lowering.bindEvents === true ? 'ensureNativeEventsBound(); ' : ''
  if (callable.completion === 'void') {
    return `export const ${callable.name} = function (${parameters}) { ${bindEvents}${requestPrelude}driverCallAsync(${callable.id}, ${operationID}, ${requestExpression}, (_data : string) => {}, (_errCode : number, _errMsg : string) => {}) }`
  }
  const valueType = promiseValueType(returnType)
  const promiseResolver = DRIVER_PROMISE_RESPONSE_RESOLVERS[callable.responseCodec]
  if (promiseResolver != null) {
    return `export const ${callable.name} = function (${parameters}) : ${returnType} { return ${promiseResolver}((resolve, reject) => { ${bindEvents}${requestPrelude}driverCallAsync(${callable.id}, ${operationID}, ${requestExpression}, resolve, reject) }) }`
  }
  const resolveExpression = driverResolveExpression(callable)
  return `export const ${callable.name} = function (${parameters}) : ${returnType} { return new Promise<${valueType}>((resolve, reject) => { ${bindEvents}${requestPrelude}driverCallAsync(${callable.id}, ${operationID}, ${requestExpression}, ${resolveExpression}, (errCode : number, errMsg : string) => { rejectNativeError(reject, errCode, errMsg) }) }) }`
}

function platformDeclaration(callable: ContractCallable, platform: Platform): string {
  if (platform !== 'harmony' && callable.lowering != null) return renderLoweredCallable(callable, platform)
  const declaration = callable.declaration?.[platform]
  if (!declaration) throw new Error(`Missing ${platform} declaration for ${callable.name}`)
  if (callable.role !== 'event-subscription') return declaration
  if (declaration.includes('@UTSJS.keepAlive')) return declaration
  return `@UTSJS.keepAlive\n${declaration}`
}

export function generateIndexFromTemplate(
  template: string,
  contract: ContractDocument,
  platform: Platform,
): string {
  const constants = contract.constants
    .map((value) => `export const ${value.name} : ${value.type} = ${value.value}`)
    .join('\n')
  const eventCallables = contract.callables
    .filter((value) => value.role !== 'operation')
    .map((value) => platformDeclaration(value, platform))
    .join('\n\n')
  const operations = contract.callables
    .filter((value) => value.role === 'operation')
    .map((value) => platformDeclaration(value, platform))
    .join('\n')
  return generatedSource(template
    .replace(INDEX_MARKERS.constants, constants)
    .replace(INDEX_MARKERS.eventCallables, eventCallables)
    .replace(INDEX_MARKERS.operations, operations)
    .replace(/\n{4,}/g, '\n\n\n')
    .trimEnd())
}

export function generateIndex(root: string, contract: ContractDocument, platform: 'android' | 'ios'): string {
  return generateIndexFromTemplate(
    readFileSync(join(root, `sdk-src/uts/app-${platform}/index.template.uts`), 'utf8'),
    contract,
    platform,
  )
}

function handlerVariable(event: ContractEvent): string {
  return `${event.name}Handlers`
}

function handlerIDVariable(event: ContractEvent): string {
  return `${event.name}HandlerIDs`
}

function removeFunction(event: ContractEvent): string {
  return `remove${event.name.slice(0, 1).toUpperCase()}${event.name.slice(1)}Handler`
}

function generateEventState(event: ContractEvent): string {
  return [
    `let ${handlerVariable(event)} : Array<${event.handlerType}> = []`,
    `let ${handlerIDVariable(event)} : Array<string> = []`,
  ].join('\n')
}

function generateEventRemoval(event: ContractEvent): string {
  const handlers = handlerVariable(event)
  const ids = handlerIDVariable(event)
  const remove = removeFunction(event)
  return `function ${remove}(subscriptionID : string) {
  const nextHandlers : Array<${event.handlerType}> = []
  const nextHandlerIDs : Array<string> = []
  for (let index : number = 0; index < ${ids}.length; index = index + 1) {
    const currentID = ${ids}[index]
    const currentHandler = ${handlers}[index]
    if (currentID != null && currentHandler != null && currentID != subscriptionID) {
      nextHandlerIDs.push(currentID)
      nextHandlers.push(currentHandler)
    }
  }
  ${ids} = nextHandlerIDs
  ${handlers} = nextHandlers
}`
}

function generateEventRegistration(event: ContractEvent): string {
  const handlers = handlerVariable(event)
  const ids = handlerIDVariable(event)
  return `export function ${event.name}Event(handler : ${event.handlerType}) : OpenIMSDKEventSubscription {
  ensureNativeEventsBound()
  const subscriptionID = nextEventHandlerID.toString()
  nextEventHandlerID = nextEventHandlerID + 1
  ${ids}.push(subscriptionID)
  ${handlers}.push(handler)
  return { id: subscriptionID, eventName: '${event.name}' }
}`
}

function generateOffSubscriptionCase(event: ContractEvent): string {
  return `    case '${event.name}':
      ${removeFunction(event)}(subscription.id)
      break
`
}

function eventDispatchArguments(event: ContractEvent): string {
  if (event.decoder.kind === 'void') return ''
  if (event.decoder.kind === 'native-error') return 'errCode, errMsg'
  if (event.decoder.kind === 'boolean') return "payload == 'true'"
  if (event.decoder.kind === 'number') return 'parseFloat(payload)'
  if (event.decoder.kind === 'raw-string') return 'payload'
  if (/^[A-Za-z_$][\w$]*$/.test(event.decoder.symbol) === false) {
    throw new Error(`Invalid event parser symbol for ${event.name}: ${event.decoder.symbol}`)
  }
  return `${event.decoder.symbol}(payload)`
}

function generateDispatchCase(event: ContractEvent, platform: 'android' | 'ios'): string {
  const handlers = handlerVariable(event)
  const args = eventDispatchArguments(event)
  const snapshot = `${event.name}DispatchSnapshot`
  const copyIndex = `${event.name}CopyIndex`
  const dispatchIndex = `${event.name}DispatchIndex`
  const current = `${event.name}CurrentHandler`
  const handler = `${event.name}DispatchHandler`
  return `    case '${event.name}':
      const ${snapshot} : Array<${event.handlerType}> = []
      for (let ${copyIndex} : number = 0; ${copyIndex} < ${handlers}.length; ${copyIndex} = ${copyIndex} + 1) {
        const ${current} = ${handlers}[${copyIndex}]
        if (${current} != null) { ${snapshot}.push(${current}) }
      }
      for (let ${dispatchIndex} : number = 0; ${dispatchIndex} < ${snapshot}.length; ${dispatchIndex} = ${dispatchIndex} + 1) {
        const ${handler} = ${snapshot}[${dispatchIndex}]
        if (${handler} != null) {
          try { ${handler}(${args}) } catch (error) { console.error('[unix-openim-sdk] ${event.name} handler failed', error) }
        }
      }
      break
`
}

function generateOffCase(event: ContractEvent): string {
  return `    case '${event.name}':
      ${handlerVariable(event)} = []
      ${handlerIDVariable(event)} = []
      break
`
}

export function generateEvents(root: string, contract: ContractDocument, platform: 'android' | 'ios'): string {
  const prelude = readFileSync(join(root, `sdk-src/uts/app-${platform}/events.prelude.uts`), 'utf8').trim()
  const state = contract.events.map(generateEventState).join('\n')
  const removals = contract.events.map(generateEventRemoval).join('\n\n')
  const registrations = contract.events.map(generateEventRegistration).join('\n\n')
  const dispatchCases = contract.events.map((event) => generateDispatchCase(event, platform)).join('\n')
  const offCases = contract.events.map(generateOffCase).join('\n')
  return generatedSource(`${prelude}

${state}
let nextEventHandlerID : number = 1
let nativeEventsBound : boolean = false

function emitSDKEvent(eventName : string, payload : string, errCode : number, errMsg : string) {
  switch (eventName) {
${dispatchCases}
    default:
      console.error('[unix-openim-sdk] ignored unknown native event: ' + eventName)
      break
  }
}

function bindNativeEvents() {
  driverBindEventSink((eventName : string, payload : string, errCode : number, errMsg : string) => {
    emitSDKEvent(eventName, payload, errCode, errMsg)
  })
}

export function ensureNativeEventsBound() {
  if (nativeEventsBound == false) {
    bindNativeEvents()
    nativeEventsBound = true
  }
}

export function offAllSDKEvents(eventName : OpenIMSDKEventName) {
  switch (eventName) {
${offCases}
  }
}

export function offSDKEvent(subscription : OpenIMSDKEventSubscription) {
  switch (subscription.eventName) {
${contract.events.map(generateOffSubscriptionCase).join('\n')}  }
}

${removals}

${registrations}`)
}

function callableInterfaceDeclaration(callable: ContractCallable): string {
  const prefix = `${callable.name}(`
  if (!callable.signature.startsWith(prefix)) throw new Error(`Invalid callable signature: ${callable.signature}`)
  const separator = callable.signature.lastIndexOf('):')
  if (separator < prefix.length) throw new Error(`Invalid callable return signature: ${callable.signature}`)
  const parameters = callable.signature.slice(prefix.length, separator)
  const returnType = callable.signature.slice(separator + 2)
  if (callable.role !== 'operation') {
    return `export declare function ${callable.name}(${parameters}) : ${returnType}`
  }
  return `export declare const ${callable.name} : (${parameters}) => ${returnType}`
}

export function generateInterface(contract: ContractDocument): string {
  const types = contract.types.map((value) => value.declaration)
  const constants = contract.constants.map((value) => `export declare const ${value.name} : ${value.type}`)
  const callables = contract.callables.map(callableInterfaceDeclaration)
  return generatedSource([...types, ...constants, ...callables].join('\n\n'))
}

export function buildSurfaceSnapshot(contract: ContractDocument): SurfaceSnapshot {
  contract = withComputedSemanticHashes(contract)
  const constants = contract.constants.map(({ id, name, type, value, signatureHash }) => ({ id, name, type, value, signatureHash }))
  const types = contract.types.map(({ id, name, signatureHash }) => ({ id, name, signatureHash }))
  const callables = contract.callables.map(({ id, name, signature, signatureHash }) => ({ id, name, signature, signatureHash }))
  const events = contract.events.map(({ id, name, callable, handlerType, signatureHash }) => ({
    id,
    name,
    callable,
    handlerType,
    signatureHash,
  }))
  const surface = { constants, types, callables, events }
  return {
    schemaVersion: 1,
    edition: contract.edition,
    counts: contract.expected,
    ...surface,
    contractHash: sha256(JSON.stringify(surface)),
  }
}

export function buildGeneratedOutputs(root: string): GeneratedOutput[] {
  const contract = readContract(root)
  const interfaceSource = generateInterface(contract)
  const snapshot = `${JSON.stringify(buildSurfaceSnapshot(contract), null, 2)}\n`
  const responseSchemas = `${JSON.stringify(buildPublicResponseSchemas(contract), null, 2)}\n`
  const testDisposition = `${JSON.stringify(buildPublicTestDisposition(contract), null, 2)}\n`
  return [
    { path: join(root, 'uni_modules/unix-openim-sdk/utssdk/interface.uts'), content: interfaceSource },
    { path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/index.uts'), content: generateIndex(root, contract, 'android') },
    { path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/index.uts'), content: generateIndex(root, contract, 'ios') },
    { path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/events.uts'), content: generateEvents(root, contract, 'android') },
    { path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/events.uts'), content: generateEvents(root, contract, 'ios') },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/OpenIMDriverRuntime.kt'),
      content: generatedSource(readFileSync(join(root, 'sdk-src/native/android/OpenIMDriverRuntime.kt'), 'utf8')),
    },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/OpenIMDriverRuntime.swift'),
      content: generatedSource(readFileSync(join(root, 'sdk-src/native/ios/OpenIMDriverRuntime.swift'), 'utf8')),
    },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/platform-driver.uts'),
      content: generatedSource(renderPlatformDriverUTS('android')),
    },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/platform-driver.uts'),
      content: generatedSource(renderPlatformDriverUTS('ios')),
    },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-android/OpenIMCoreAdapter.kt'),
      content: generatedSource(renderNativeCoreAdapter(contract, 'android')),
    },
    {
      path: join(root, 'uni_modules/unix-openim-sdk/utssdk/app-ios/OpenIMCoreAdapter.swift'),
      content: generatedSource(renderNativeCoreAdapter(contract, 'ios')),
    },
    { path: join(root, 'contracts/base/surface.snapshot.json'), content: snapshot },
    { path: join(root, 'contracts/base/response-schemas.json'), content: responseSchemas },
    { path: join(root, 'contracts/base/test-disposition.json'), content: testDisposition },
  ].map((output) => ({ ...output, content: output.content.endsWith('\n') ? output.content : `${output.content}\n` }))
}

export function generate(root: string): GeneratedOutput[] {
  const outputs = buildGeneratedOutputs(root)
  for (const output of outputs) {
    mkdirSync(dirname(output.path), { recursive: true })
    writeFileSync(output.path, output.content)
  }
  return outputs
}
