import { extractExportedValues, type ParsedSource } from './source.js'

export const INDEX_MARKERS = {
  constants: '// <openim-generated:constants>',
  eventCallables: '// <openim-generated:event-callables>',
  operations: '// <openim-generated:operations>',
} as const

/**
 * Builds the canonical forward-generation template during an explicitly approved
 * façade migration. Normal generation consumes the resulting sdk-src template and
 * never reads implementation bodies from generated façade outputs.
 */
export function makeIndexTemplate(
  parsed: ParsedSource,
  constants: Set<string>,
  eventCallables: Set<string>,
  operations: Set<string>,
): string {
  type Replacement = { start: number; end: number; value: string }
  const replacements: Replacement[] = []
  const inserted = { constants: false, eventCallables: false, operations: false }
  const exported = extractExportedValues(parsed)
  for (const value of exported) {
    let category: keyof typeof inserted | undefined
    if (constants.has(value.name)) category = 'constants'
    else if (eventCallables.has(value.name)) category = 'eventCallables'
    else if (operations.has(value.name)) category = 'operations'
    if (!category) continue
    const marker = inserted[category] ? '' : INDEX_MARKERS[category]
    inserted[category] = true
    replacements.push({
      start: value.node.getStart(parsed.sourceFile),
      end: value.node.end,
      value: marker,
    })
  }
  let output = parsed.text
  replacements.sort((left, right) => right.start - left.start)
  for (const replacement of replacements) {
    output = output.slice(0, replacement.start) + replacement.value + output.slice(replacement.end)
  }
  for (const [category, present] of Object.entries(inserted)) {
    if (!present) throw new Error(`Failed to create index template marker ${category}`)
  }
  return output
    .replace(/^\/\/ @generated by OpenIM Contract Compiler; DO NOT EDIT\.\n/, '')
    .replace(/\n{4,}/g, '\n\n\n')
    .replace(
      /\/\/ <openim-generated:event-callables>\n+\/\/ <openim-generated:operations>\n*$/,
      '// <openim-generated:event-callables>\n\n// <openim-generated:operations>\n',
    )
}
